### ISSUE TITLE
Learning Spaces page scrolling issue in safari web browser

### ISSUE THREAD

**Issue by chaitanyabhardwaj** [alteducation/web#6]
https://www.alternativeeducation.in/learning-spaces
On pressing 'See Full Information' on any particular card, it expands.
**Issue** - The scrolling is non-fluent and a bit laggy in Safari while it's smooth in chrome(70.0.3538.77) and firefox(63.0b14)
**Tested on** - Safari(12.0.1 ) macos(10.14.1)

**Comment by ghost** [comment]
I'm aware of the issue, the scrolling works well inside the modal container. There was no proper way to make it work when the mouse pointer is outside the modal container due to browser implementation standards

I have plans to change the 'See full information' page from a JavaScript Modal View to a full html page. So the issue will be non existent and we will be able to display much more information. Once that work is completed the issue will be addressed.

Thank you.
